### PR TITLE
Added using directive on variables to ensure cleanup

### PR DESCRIPTION
**Pull request by sleepy-day**
For #240, set on FileStream types as well as a few others if it was used elsewhere. 

## Summary by CodeRabbit

- **New Features**
	- Improved resource management across multiple controllers for better handling of file streams, ensuring they are disposed of correctly after use.

- **Bug Fixes**
	- Addressed potential resource leaks in methods related to file handling by introducing `using` statements.

- **Documentation**
	- Updated method signatures for better clarity on resource management practices, though parameters and return types remain unchanged.

### CODE REVIEW

**Comment by sleepy-day** [comment]
Accidentally added using for a MetadataContext that causes issues, removed it now.

**Comment by AngeloTadeucci** [comment]
Navmesh loading is fine too?

**Comment by sleepy-day** [comment]
> Navmesh loading is fine too?
I will check it out and let you know, I think I missed a change that I gotta fix first before ingest will run properly for me (it's broken).

**Comment by sleepy-day** [comment]
No issues on navmesh loading.

**Review by AngeloTadeucci — APPROVED** [review]

**Review by Zintixx — APPROVED** [review]

**Comment by AngeloTadeucci** [comment]
@sleepy-day sorry but I'm reverting this pull request, nothing to do with what you did but the suggestion for coderabbit was invalid..

**Pull request merged**
